### ISSUE TITLE
Capturing errors in connection

### ISSUE THREAD

**Issue by rupertbg** [thejsj/rethinkdb-init#12]
Is there a way to capture errors e.g. from `.then(error, connection` .. ?

**Comment by thejsj** [comment]
All functions here return a Promise. That means that you can use `Promise.catch` to capture errors.

```
r.init(opts)
.then(function (conn) {
  // All tables and indexes have been created
})
.catch(function (err) {
  // Retry????
});
```

Closing this issue, but happy to reopen it if there's anything else.
