### ISSUE TITLE
Compatibility with `rethinkdbdash`

### ISSUE THREAD

**Issue by marshall007** [thejsj/rethinkdb-init#9]
I think the only thing that would be required to make this compatible with the unofficial [`rethinkdbdash`](https://github.com/neumino/rethinkdbdash) driver is on this line: [`/index.js#L25`](https://github.com/thejsj/rethinkdb-init/blob/master/index.js#L25). Errors generated from `rethinkdbdash` have a `message` property instead of `msg`.

@thejsj would you accept a PR that changes this line to `(err.msg || err.message).indexOf(...)`?

**Comment by thejsj** [comment]
Absolutely. Go for it!

**Comment by sagivf** [comment]
:+1:
